# Generated by Django 4.2.11 on 2024-03-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.CharField(max_length=200)),
                ('item_quantity', models.CharField(max_length=200)),
            ],
        ),
    ]
